version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Map port 3000 on the host to port 3000 in the container
    volumes:
      - frontend-build:/frontend/build  # Volume for the frontend build output
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=production  # Ensure production mode in Docker Compose

  backend:
    build:
      context: ./backend  # Path to the backend directory
      dockerfile: Dockerfile
    ports:
      - "8000:80"  # Map port 8000 on the host to port 80 in the container
    volumes:
      - frontend-build:/frontend/build  # Mount the same volume to the backend
    depends_on:
      - frontend
      - db  # Add dependency on the PostgreSQL service
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/mydatabase  # Connection string for PostgreSQL
    command: ["sh", "-c", "while ! [ -d /frontend/build/static ]; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0 --port 80"]  # Wait for static files

  db:
    image: postgres:latest
    restart: always
    env_file:
      - ./backend/.env  # Load environment variables from the .env file
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  frontend-build:
  postgres_data:  # Named volume for PostgreSQL data
